// Inspection Checklist - Structural Steelworks

export const wellbeingQuestions = [
  {
    id: 1,
    text: "RFI No.",
    type: "short-answer",
    section: "Project Information",
    optional: false,
  },
  {
    id: 2,
    text: "PROJECT",
    type: "short-answer",
    section: "Project Information",
    optional: false,
  },
  {
    id: 3,
    text: "DATE",
    type: "date",
    section: "Project Information",
    optional: false,
  },
  {
    id: 4,
    text: "STRUCTURAL STEEL SPECIALIST",
    type: "short-answer",
    section: "Project Information",
    optional: false,
  },
  {
    id: 5,
    text: "LOCATION / GRIDLINES",
    type: "short-answer",
    section: "Project Information",
    optional: false,
  },
  {
    id: 6,
    text: "STEEL GRADE",
    type: "short-answer",
    section: "Project Information",
    optional: false,
  },
  {
    id: 7,
    text: "CLASS OF STEEL (CHECK CONSULTANT DRAWING)",
    type: "short-answer",
    section: "Project Information",
    optional: false,
  },
  {
    id: 8,
    text: "FINISHING SPECIFICATION",
    type: "radio",
    options: ["HOT DIPPED GALVANISED", "PAINTING", "VERMICULITE", "INTUMESCENT"],
    section: "Project Information",
    optional: false,
  },
  {
    id: 9,
    text: "STRUCTURAL ELEMENT",
    type: "radio",
    options: ["BEAM", "COLUMN", "OTHERS"],
    section: "Project Information",
    optional: false,
  },
  // Site Preparation
  {
    id: 11,
    text: " Weight of the steel element (to make sure of tower crane lifting capacity)",
    type: "dual-response-date",
    section: "Site Preparation",
    optional: false,
  },
  {
    id: 12,
    text: " Temporary propping of the steel elements (YES/NO)",
    type: "dual-response-date",
    section: "Site Preparation",
    optional: false,
  },
  {
    id: 13,
    text: " Lifting position / lifting gears",
    type: "dual-response-date",
    section: "Site Preparation",
    optional: false,
  },
  {
    id: 14,
    text: "Approved lane / road closure from LTA (if crane parking is at road)",
    type: "dual-response-date",
    section: "Site Preparation",
    optional: false,
  },
  {
    id: 15,
    text: " Crane sitting platform with PE calculation & COS",
    type: "dual-response-date",
    section: "Site Preparation",
    optional: false,
  },
  {
    id: 16,
    text: " LEW engagement (as per contract requirement)",
    type: "dual-response-date",
    section: "Site Preparation",
    optional: false,
  },

  // Surface Preparation
  {
    id: 17,
    text: " Anchor Bolts: Position (mm) (at top of concrete) [Criteria: ± 5mm]",
    type: "dual-response-date",
    section: "Surface Preparation",
    optional: false,
  },
  {
    id: 18,
    text: " Bolt Level / Double Nut < 3 threads or more: Bolt Size (mm) (as specified)",
    type: "dual-response-date",
    section: "Surface Preparation",
    optional: false,
  },
  {
    id: 19,
    text: " Bolt Level / Double Nut: Hole Size (mm) and thickness (mm)",
    type: "dual-response-date",
    section: "Surface Preparation",
    optional: false,
  },
  {
    id: 20,
    text: " Cleanliness of the drill holes",
    type: "dual-response-date",
    section: "Surface Preparation",
    optional: false,
  },
  {
    id: 21,
    text: " Non-shrink Grout Bedding: Grade (N/mm2 same or higher than concrete)",
    type: "dual-response-date",
    section: "Surface Preparation",
    optional: false,
  },
  {
    id: 22,
    text: " Non-shrink Grout Bedding: Thickness as specified",
    type: "dual-response-date",
    section: "Surface Preparation",
    optional: false,
  },

  // Dimension Check Before Welding (Fit-Up)
  {
    id: 23,
    text: "Overall Plan Dimension (Permissible Deviation): Dimension for L <= 30m and for L > 30m",
    type: "dual-response-date",
    section: "Dimension Check Before Welding (Fit-Up)",
    optional: false,
  },
  {
    id: 24,
    text: "Alignment: from grid line",
    type: "dual-response-date",
    section: "Dimension Check Before Welding (Fit-Up)",
    optional: false,
  },
  {
    id: 25,
    text: "Position of Column at base",
    type: "dual-response-date",
    section: "Dimension Check Before Welding (Fit-Up)",
    optional: false,
  },
  {
    id: 26,
    text: "Column Plumb: Dh = h/600 or 5mm (ΔH = 5mm max)",
    type: "dual-response-date",
    section: "Dimension Check Before Welding (Fit-Up)",
    optional: false,
  },
  {
    id: 27,
    text: "Gap between bearing surfaces (D>1000-1)mm where D is the dimension along bearing surface",
    type: "dual-response-date",
    section: "Dimension Check Before Welding (Fit-Up)",
    optional: false,
  },
  {
    id: 28,
    text: "Level of Beams: i) 2 or more beams meeting at a column",
    type: "dual-response-date",
    section: "Dimension Check Before Welding (Fit-Up)",
    optional: false,
  },
  {
    id: 29,
    text: "Level of Beams: ii) Level of beam at its ends",
    type: "dual-response-date",
    section: "Dimension Check Before Welding (Fit-Up)",
    optional: false,
  },
  {
    id: 30,
    text: "Level of Beams: iii) Level of adjacent beams within 5m",
    type: "dual-response-date",
    section: "Dimension Check Before Welding (Fit-Up)",
    optional: false,
  },
  {
    id: 31,
    text: "Level of Beams: iv) specified beam level at support column",
    type: "dual-response-date",
    section: "Dimension Check Before Welding (Fit-Up)",
    optional: false,
  },
  {
    id: 32,
    text: "Level of Beams: v) beam position relative to adjacent beam above or below (h<3m or h>3m)",
    type: "dual-response-date",
    section: "Dimension Check Before Welding (Fit-Up)",
    optional: false,
  },
  {
    id: 33,
    text: "TOP of column at the left (RL)",
    type: "dual-response-date",
    section: "Dimension Check Before Welding (Fit-Up)",
    optional: false,
  },
  {
    id: 34,
    text: "TOP of column at the right (RL)",
    type: "dual-response-date",
    section: "Dimension Check Before Welding (Fit-Up)",
    optional: false,
  },

  // Dimension Check After Welding
  {
    id: 35,
    text: "Overall Plan Dimension (Permissible Deviation): Dimension for L <= 30m and for L > 30m",
    type: "dual-response-date",
    section: "Dimension Check After Welding",
    optional: false,
  },
  {
    id: 36,
    text: "Alignment: from grid line",
    type: "dual-response-date",
    section: "Dimension Check After Welding",
    optional: false,
  },
  {
    id: 37,
    text: "Position of Column at base",
    type: "dual-response-date",
    section: "Dimension Check After Welding",
    optional: false,
  },
  {
    id: 38,
    text: "Column Plumb: Dh = h/600 or 5mm (ΔH = 5mm max)",
    type: "dual-response-date",
    section: "Dimension Check After Welding",
    optional: false,
  },
  {
    id: 39,
    text: "Gap between bearing surfaces (D>1000-1)mm where D is the dimension along bearing surface",
    type: "dual-response-date",
    section: "Dimension Check After Welding",
    optional: false,
  },
  {
    id: 40,
    text: "Level of Beams: i) 2 or more beams meeting at a column",
    type: "dual-response-date",
    section: "Dimension Check After Welding",
    optional: false,
  },
  {
    id: 41,
    text: "Level of Beams: ii) Level of beam at its ends",
    type: "dual-response-date",
    section: "Dimension Check After Welding",
    optional: false,
  },
  {
    id: 42,
    text: "Level of Beams: iii) Level of adjacent beams within 5m",
    type: "dual-response-date",
    section: "Dimension Check After Welding",
    optional: false,
  },
  {
    id: 43,
    text: "Level of Beams: iv) specified beam level at support column",
    type: "dual-response-date",
    section: "Dimension Check After Welding",
    optional: false,
  },
  {
    id: 44,
    text: "Level of Beams: v) beam position relative to adjacent beam above or below (h<3m or h>3m)",
    type: "dual-response-date",
    section: "Dimension Check After Welding",
    optional: false,
  },
  {
    id: 45,
    text: "Bondek: i) reference level (RL)",
    type: "dual-response-date",
    section: "Dimension Check After Welding",
    optional: false,
  },
  {
    id: 46,
    text: "Position / orientation",
    type: "dual-response-date",
    section: "Dimension Check After Welding",
    optional: false,
  },

  // Inspection on Bolting
  {
    id: 47,
    text: "Pre-Tighten: Check fit-up and alignment of components assembly",
    type: "dual-response-date",
    section: "Inspection on Bolting",
    optional: false,
  },
  {
    id: 48,
    text: "Pre-Tighten: HSFG/Mild Steel Bolts",
    type: "dual-response-date",
    section: "Inspection on Bolting",
    optional: false,
  },
  {
    id: 49,
    text: "Pre-Tighten: Bolt Size",
    type: "dual-response-date",
    section: "Inspection on Bolting",
    optional: false,
  },
  {
    id: 50,
    text: "Pre-Tighten: Bolt Numbers",
    type: "dual-response-date",
    section: "Inspection on Bolting",
    optional: false,
  },
  {
    id: 51,
    text: "Pre-Tighten: Bolt hole size",
    type: "dual-response-date",
    section: "Inspection on Bolting",
    optional: false,
  },
  {
    id: 52,
    text: "Fully Tightened: Exposed thread length",
    type: "dual-response-date",
    section: "Inspection on Bolting",
    optional: false,
  },
  {
    id: 53,
    text: "Fully Tightened: Torque wrench tightening",
    type: "dual-response-date",
    section: "Inspection on Bolting",
    optional: false,
  },
  {
    id: 54,
    text: "Fully Tightened: Torque wrench calibration certificate",
    type: "dual-response-date",
    section: "Inspection on Bolting",
    optional: false,
  },

  // Welding
  {
    id: 55,
    text: "Before Welding: Condition of welding equipment",
    type: "dual-response-date",
    section: "Welding",
    optional: false,
  },
  {
    id: 56,
    text: "Before Welding: Quality and condition of base and filler materials",
    type: "dual-response-date",
    section: "Welding",
    optional: false,
  },
  {
    id: 57,
    text: "Before Welding: Weld joint cleanliness",
    type: "dual-response-date",
    section: "Welding",
    optional: false,
  },
  {
    id: 58,
    text: "Before Welding: Pre-heat when required",
    type: "dual-response-date",
    section: "Welding",
    optional: false,
  },
  {
    id: 59,
    text: "During Welding: Interpass cleaning",
    type: "dual-response-date",
    section: "Welding",
    optional: false,
  },
  {
    id: 60,
    text: "During Welding: Interpass temperature",
    type: "dual-response-date",
    section: "Welding",
    optional: false,
  },
  {
    id: 61,
    text: "During Welding: Placement and sequencing of individual weld passes",
    type: "dual-response-date",
    section: "Welding",
    optional: false,
  },
  {
    id: 62,
    text: "During Welding: Check for back gouged surfaces",
    type: "dual-response-date",
    section: "Welding",
    optional: false,
  },
  {
    id: 63,
    text: "During Welding: In-process NDT if required",
    type: "dual-response-date",
    section: "Welding",
    optional: false,
  },
  {
    id: 64,
    text: "After Welding: finished weld appearance",
    type: "dual-response-date",
    section: "Welding",
    optional: false,
  },
  {
    id: 65,
    text: "After Welding: weld size (mm)",
    type: "dual-response-date",
    section: "Welding",
    optional: false,
  },
  {
    id: 66,
    text: "After Welding: weld length (mm)",
    type: "dual-response-date",
    section: "Welding",
    optional: false,
  },
  {
    id: 67,
    text: "After Welding: dimensional accuracy of weldment",
    type: "dual-response-date",
    section: "Welding",
    optional: false,
  },
  {
    id: 68,
    text: "After Welding: additional NDT if required",
    type: "dual-response-date",
    section: "Welding",
    optional: false,
  },
  {
    id: 69,
    text: "After Welding: post weld heat treatment if required",
    type: "dual-response-date",
    section: "Welding",
    optional: false,
  },

  // Post Installation Testing
  {
    id: 70,
    text: "MPI/UT/RT testing",
    type: "dual-response-date",
    section: "Post Installation Testing",
    optional: false,
  },

  // Finishing
  {
    id: 71,
    text: "Painting touch up",
    type: "dual-response-date",
    section: "Finishing",
    optional: false,
  },
  {
    id: 72,
    text: "Fire proofing requirement (vermiculite/fibre wrap)",
    type: "dual-response-date",
    section: "Finishing",
    optional: false,
  },

  // Signatures
  {
    id: 901,
    text: "Remarks",
    type: "textarea",
    section: "Signatures",
    optional: true,
  },
  {
    id: 902,
    text: "Subcon Rep Name",
    type: "short-answer",
    section: "Signatures",
    optional: false,
  },
  {
    id: 903,
    text: "Subcon Rep Date",
    type: "date",
    section: "Signatures",
    optional: false,
  },
  {
    id: 904,
    text: "Subcon Rep Signature",
    type: "signature",
    section: "Signatures",
    optional: false,
  },
  {
    id: 905,
    text: "Main Con Name",
    type: "short-answer",
    section: "Signatures",
    optional: false,
  },
  {
    id: 906,
    text: "Main Con Date",
    type: "date",
    section: "Signatures",
    optional: false,
  },
  {
    id: 907,
    text: "Main Con Signature",
    type: "signature",
    section: "Signatures",
    optional: false,
  },
  {
    id: 908,
    text: "SRE Name",
    type: "short-answer",
    section: "Signatures",
    optional: false,
  },
  {
    id: 909,
    text: "SRE Date",
    type: "date",
    section: "Signatures",
    optional: false,
  },
  {
    id: 910,
    text: "SRE Signature",
    type: "signature",
    section: "Signatures",
    optional: false,
  },
];

export const slug = "structural-steelworks";
export const assessmentId = "super-user-assignment-id"; // Using ID from WelcomePage mock for consistency
